<?php
declare(strict_types=1);

namespace common\CQS\Domain\Interface\Storage;

use RuntimeException;

/**
 * Interface FileStorageInterface
 * Defines a contract for interacting with a file storage system.
 */
interface FileStorageInterface
{
    /**
     * Adds a file to storage
     * @param string $file file which needs to be added, must contain full path
     * @param string $origin origin file name if it's differ from current name
     * @param boolean $delete delete origin file after it's been added
     * @return string storage file name (can contain path from baseDir)
     * @throws RuntimeException
     */
    public function put(
        string $file,
        ?string $origin = null,
        bool $delete = true
    ): string;

    /**
     * Get direct URL to the file
     * @param string $name the file name returned by @see Storage::add
     * @param boolean $absolute return absolute url
     * @return string file URL
     */
    public function get(string $name, bool $absolute = false): string;

    /**
     * Check if file with given name is exists in storage
     * @param string $name file name generated by Storage::add
     * @return boolean
     */
    public function exists(string $name): bool;

    /**
     * Removes file from storage
     * @param string $name File name generated by @see Storage::add
     * @return boolean
     */
    public function delete(string $name): bool;

    public function getFileSize(string $name): int;
}